# Generated by Django 5.2.5 on 2026-01-18 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_prestamos', '0026_prestamo_fecha_aprobacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaConfiguracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la Empresa')),
                ('rnc', models.CharField(blank=True, max_length=50, null=True, verbose_name='RNC o Identificación Fiscal')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo de la Empresa')),
            ],
            options={
                'verbose_name': 'Configuración de la Empresa',
                'verbose_name_plural': 'Configuración de la Empresa',
            },
        ),
    ]
