# Generated by Django 5.2.5 on 2026-01-19 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_prestamos', '0027_empresaconfiguracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpresoraConfiguracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Impresora de Tiques Principal', max_length=100, verbose_name='Nombre de la Configuración')),
                ('ancho_papel_px', models.PositiveIntegerField(default=300, verbose_name='Ancho del Papel (en píxeles)')),
                ('incluir_logo', models.BooleanField(default=True, verbose_name='¿Incluir logo en el recibo?')),
                ('margen_superior_px', models.PositiveIntegerField(default=10, verbose_name='Margen Superior (en píxeles)')),
                ('margen_inferior_px', models.PositiveIntegerField(default=10, verbose_name='Margen Inferior (en píxeles)')),
            ],
            options={
                'verbose_name': 'Configuración de Impresora',
                'verbose_name_plural': 'Configuración de Impresora',
            },
        ),
        migrations.AlterModelOptions(
            name='empresaconfiguracion',
            options={},
        ),
    ]
